### ISSUE TITLE
variables

### ISSUE THREAD

**Issue by bhanuvrat** [theskumar/dotfiles#2]
So where do you put all your environment variables? directly in .zshrc?
this does not take long but ... I would like it to be present automatically ...

```
ANSIBLE_NOCOWS=1
```

disables cowsay : http://docs.ansible.com/faq.html#how-do-i-disable-cowsay
I don't think you like cows on terminal either ...

**Comment by theskumar** [comment]
The environment variables goes into `.exports`. I add this  `ANSIBLE_NOCOWS=1` to it a while back https://github.com/theskumar/dotfiles/commit/46e3db1ff6be5d2f58d1401e5c970d6b1827d40c you should be able to update your local copy with `git pull --rebase` ;)
